real_estate/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
]

real_estate/listing/urls.py
from django.urls import path
from . import views

app_name = 'listing'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:listing_id>', views.detail, name='detail'),
    path('search', views.search, name='search'),
]

real_estate/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='main-index'),
    path('about/', views.about, name='main-about'),
]

real_estate/real_estate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('listing/', include('listing.urls')),
    path('account/', include('account.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

real_estate/templates/partials/_footer.html
{% load static %}
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy; 2019 Real Estate
</footer>

real_estate/templates/partials/_messages.html
{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert" id="alert_box">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
    <script>
        let stIdAndFadeOut = setTimeout(function () {
            $('#alert_box').fadeOut();
        }, 5000);
    </script>
</div>
{% endfor %}
{% endif %}

real_estate/templates/partials/_navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main:main-index' %}">
            <img src="{% static 'main/img/logo.png' %}" class="logo" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <li class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'main:main-index' %}">Home</a>
                </li>
                <li class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'main:main-about' %}">About</a>
                </li>
                <li class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'listing:index' %}">Featured Listings</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_active %}
                    <li class="nav-item mr-3">
                        <a href="{% url 'account:dashboard' %}" class="nav-link">
                            Welcome {{ user.username }} (Dashboard)</a>
                    </li>
                    <li class="nav-item mr-3">
                        <a href="{% url 'account:logout' %}" class="nav-link">
                            <i class="fas fa-sign-out-alt"></i>
                            Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item mr-3">
                        <a class="nav-link" href="{% url 'account:register' %}">
                            <i class="fas fa-user-plus"></i> Register</a>
                    </li>
                    <li class="nav-item mr-3">
                        <a class="nav-link" href="{% url 'account:login' %}">
                            <i class="fas fa-sign-in-alt"></i>

                            Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

real_estate/templates/partials/_topbar.html
{% load static %}
<!-- Top Bar -->
<section id="top-bar" class="p-3">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <i class="fas fa-phone"></i> (666)-666-666
      </div>
      <div class="col-md-4">
        <i class="fas fa-envelope-open"></i> contact@realestate.com
      </div>
      <div class="col-md-4">
        <div class="social text-right">
          <a href="#">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="#">
            <i class="fab fa-facebook"></i>
          </a>
          <a href="#">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="#">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="#">
            <i class="fab fa-pinterest"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>