real_estate/contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contactView, name='contact'),
]

real_estate/listing/urls.py
from django.urls import path
from . import views

app_name = 'listing'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:listing_id>', views.detail, name='detail'),
    path('search', views.search, name='search'),
]

real_estate/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='main-index'),
    path('about/', views.about, name='main-about'),
]

real_estate/real_estate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('listing/', include('listing.urls')),
    path('account/', include('account.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

real_estate/listing/models.py
from django.db import models
from datetime import datetime
from realtor.models import Realtors

# Create your models here.


class Listings(models.Model):
    listing_id = models.AutoField(
        verbose_name='ID',
        primary_key=True,
    )
    realtor_id = models.ForeignKey(Realtors, on_delete=models.DO_NOTHING)
    listing_title = models.CharField(
        max_length=100,
        verbose_name='Title',
    )
    street = models.CharField(max_length=100, verbose_name='Street')
    city = models.CharField(max_length=100, verbose_name='City')
    state = models.CharField(max_length=100, verbose_name='State')
    zipcode = models.CharField(max_length=100, verbose_name='ZipCode')
    description = models.TextField(blank=True, verbose_name='Description')
    price = models.DecimalField(
        verbose_name='Price', max_digits=15, decimal_places=5)
    bedroom = models.IntegerField(verbose_name='Bedroom')
    bathroom = models.DecimalField(
        verbose_name='Bathroom', max_digits=2, decimal_places=1)
    garage = models.IntegerField(default=0, verbose_name='Garage')
    sqft = models.IntegerField(verbose_name='Sqft')
    lot_size = models.DecimalField(
        max_digits=5, decimal_places=1, verbose_name='Lot Size')
    photo_main = models.ImageField(
        upload_to='photos/%Y/%m/%d/', verbose_name='Main Photo')
    is_published = models.BooleanField(default=True, verbose_name='Published')
    list_date = models.DateTimeField(
        default=datetime.now, blank=True, verbose_name='List Date')

    class Meta():
        verbose_name = 'Listing'
        verbose_name_plural = 'Listings'

    def __str__(self):
        return self.listing_title


class Photos(models.Model):
    listing_id = models.ForeignKey(Listings, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)

    class Meta():
        verbose_name = 'Photo'
        verbose_name_plural = 'Photos'

real_estate/listing/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .models import Listings, Photos
from .choices import bedroom_choices, price_choices, state_choices
from contact.forms import InquiryModelForm
from django.contrib import messages
# Create your views here.


def index(request):
    title = 'Real Estate | Listing'
    template = 'listing/index.html'

    # Order & Filter the context for the listing page.
    listings = Listings.objects.all().order_by(
        '-list_date').filter(is_published=True)

    paginator = Paginator(listings, 6)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)

    context = {'title': title,
               'listings': paged_listings,
               }
    return render(request, template, context)


def detail(request, listing_id):
    title = 'Listing | Details'
    template_name = 'listing/detail.html'
    details = get_object_or_404(Listings, pk=listing_id)
    photos = Photos.objects.all().filter(listing_id=listing_id)
    if request.user.is_active:
        inquiry_form = InquiryModelForm(initial={
            'listing_id': listing_id,
            'listing_title': getattr(details, 'listing_title'),
            'contact_name': request.user.first_name + ' ' + request.user.last_name,
            'contact_mail': request.user.email,
            'user_id': request.user.id,
        })

    if request.user.is_anonymous:
        inquiry_form = InquiryModelForm(initial={
            'listing_id': listing_id,
            'listing_title': getattr(details, 'listing_title'),
        })

    context = {
        'title': title,
        'details': details,
        'photos': photos,
        'inquiry_form': inquiry_form,
    }
    return render(request, template_name, context)


def search(request):
    title = 'Search Result'
    template = 'listing/search.html'

    queryset_list = Listings.objects.order_by('-list_date')
    # Keywords
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(
                description__icontains=keywords)
    # City
    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            queryset_list = queryset_list.filter(
                city__iexact=city)
    # State
    if 'state' in request.GET:
        state = request.GET['state']
        if state:
            queryset_list = queryset_list.filter(
                state__iexact=state)
    # Bedrooms
    if 'bedrooms' in request.GET:
        bedroom = request.GET['bedrooms']
        if bedroom:
            queryset_list = queryset_list.filter(
                bedroom__lte=bedroom)
    # Price
    if 'price' in request.GET:
        price = request.GET['price']
        if price:
            queryset_list = queryset_list.filter(
                price__lte=price)
    context = {'title': title,
               'listings': queryset_list,
               'state_choices': state_choices,
               'bedroom_choices': bedroom_choices,
               'price_choices': price_choices,
               }
    return render(request, template, context)

real_estate/listing/templates/listing/detail.html
{% extends 'header/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">{{details.listing_title}}</h1>
                <p class="lead">
                    <i class="fas fa-map-marker"></i> {{details.city}} {{details.state}}, {{details.zipcode}}</p>
            </div>
        </div>
    </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'main:main-index' %}">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'listing:index' %}">Listings</a>
                </li>
                <li class="breadcrumb-item active">{{details.listing_title}}</li>
            </ol>
        </nav>
    </div>
</section>

<!-- Listing -->
<section id="listing" class="py-4">
    <div class="container">
        <a href="{% url 'listing:index' %}" class="btn btn-light mb-4">Back To Listings</a>
        <div class="row">
            <div class="col-md-9">
                <!-- Home Main Image -->
                <img src="{{details.photo_main.url}}" alt="" class="img-main img-fluid mb-3">
                <!-- Thumbnails -->
                <div class="row mb-5 thumbs">
                    {% if photos %}
                    {% for p in photos %}
                    <div class="col-md-2">
                        <a href="{{p.photo.url}}" data-lightbox="home-images">
                            <img src="{{p.photo.url}}" alt="" class="img-fluid">
                        </a>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
                <!-- Fields -->
                <div class="row mb-5">
                    <div class="col-md-6">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-money-bill-alt"></i> Asking Price:
                                <span class="float-right">${{details.price | intcomma}}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-bed"></i> Bedrooms:
                                <span class="float-right">{{details.bedroom}}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-bath"></i> Bathrooms:
                                <span class="float-right">{{details.bathroom}}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-car"></i> Garage:
                                <span class="float-right">{{details.garage}}
                                </span>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-th-large"></i> Square Feet:
                                <span class="float-right">{{details.sqft}}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-square"></i> Lot Size:
                                <span class="float-right">{{details.lot_size}} Acres
                                </span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-calendar"></i> Listing Date:
                                <span class="float-right">{{details.list_date | date}}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-bed"></i> Realtor:
                                <span class="float-right">{{details.realtor_id}}
                                </span>
                            </li>


                        </ul>
                    </div>
                </div>

                <!-- Description -->
                <div class="row mb-5">
                    <div class="col-md-12">
                        {{details.description}}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card mb-3">
                    <img class="card-img-top" src="{{details.realtor_id.photo.url}}" alt="Seller of the month">
                    <div class="card-body">
                        <h5 class="card-title">Property Realtor</h5>
                        <h6 class="text-secondary">{{details.realtor_id}}</h6>
                    </div>
                </div>
                <button class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Make An
                    Inquiry</button>
            </div>
        </div>
    </div>
</section>

<!-- Inquiry Modal -->
<div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% if inquiry_form %}
                <form action="{% url 'contact:contact' %}" method="POST">
                    {% csrf_token %}
                    {{inquiry_form}}
                    <hr>
                    <input type="submit" value="Send" class="btn btn-block btn-secondary">
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

real_estate/listing/templates/listing/index.html
{% extends 'header/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">Browse Our Properties</h1>
                <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
            </div>
        </div>
    </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'main:main-index' %}">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item active"> Browse Listings</li>
            </ol>
        </nav>
    </div>
</section>

<!-- Listings -->
<section id="listings" class="py-4">
    <div class="container">
        <div class="row">
            {% if listings %}
            {% for listing in listings %}
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card">
                    <img class="card-img-top" height="200" src="{{listing.photo_main.url}}" alt="">
                    <div class="card-img-overlay">
                        <h2>
                            <span
                                class="badge badge-secondary text-white">${{listing.price | floatformat:0 | intcomma}}</span>
                        </h2>
                    </div>
                    <div class="card-body">
                        <div class="listing-heading text-center">
                            <h4 class="text-primary">{{listing.listing_title}}</h4>
                            <p>
                                <i class="fas fa-map-marker text-secondary"></i> {{listing.city}} {{listing.state}},
                                {{listing.zipcode}}</p>
                        </div>
                        <hr>
                        <div class="row py-2 text-secondary">
                            <div class="col-6">
                                <i class="fas fa-th-large"></i> Sqft: {{listing.sqft}}</div>
                            <div class="col-6">
                                <i class="fas fa-car"></i> Garage: {{listing.garage}}</div>
                        </div>
                        <div class="row py-2 text-secondary">
                            <div class="col-6">
                                <i class="fas fa-bed"></i> Bedrooms: {{listing.bedroom}}</div>
                            <div class="col-6">
                                <i class="fas fa-bath"></i> Bathrooms: {{listing.bathroom}}</div>
                        </div>
                        <hr>
                        <div class="row py-2 text-secondary">
                            <div class="col-12">
                                <i class="fas fa-user"></i> {{listing.realtor_id}}</div>
                        </div>
                        <div class="row text-secondary pb-2">
                            <div class="col-6">
                                <i class="fas fa-clock"></i> {{ listing.list_date | timesince }} </div>
                        </div>
                        <hr>
                        <a href="{% url 'listing:detail' listing.listing_id %}" class="btn btn-primary btn-block">More
                            Info</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-md-12">
                <p>There are no listings</p>
            </div>
            {% endif %}
        </div>

        <div class="row">
            <div class="col-md-12">
                {% if listings.has_other_pages %}
                <ul class="pagination">
                    <!-- LISTINGS HAS PREVIOUS -->
                    {% if listings.has_previous %}
                    <li class="page-item">
                        <a href="?page={{listings.previous_page_number}}" class="page-link">&laquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&laquo;</a>
                    </li>
                    {% endif %}
                    {% for page_number in listings.paginator.page_range %}
                    {% if listings.number == page_number %}
                    <li class="page-item active">
                        <a class="page-link">{{page_number}}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a href="?page={{page_number}}" class="page-link">{{page_number}}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    <!-- LISTINGS HAS NEXT -->
                    {% if listings.has_next %}
                    <li class="page-item">
                        <a href="?page={{listings.next_page_number}}" class="page-link">&raquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

real_estate/listing/templates/listing/search.html
{% extends 'header/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<section id="showcase-inner" class="showcase-search text-white py-5">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <form action="{% url 'listing:search' %}">
                    <!-- Form Row 1 -->
                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label class="sr-only">Keywords</label>
                            <input type="text" name="keywords" class="form-control"
                                placeholder="Keyword (Pool, Garage, etc)">
                        </div>

                        <div class="col-md-4 mb-3">
                            <label class="sr-only">City</label>
                            <input type="text" name="city" class="form-control" placeholder="City">
                        </div>

                        <div class="col-md-4 mb-3">
                            <label class="sr-only">State</label>
                            <select name="state" class="form-control">
                                <option selected="true" disabled="disabled">State (All)</option>
                                {% for key, value in state_choices.items %}
                                <option value="{{ key }}">{{ value }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <!-- Form Row 2 -->
                    <div class="form-row">
                        <div class="col-md-6 mb-3">
                            <label class="sr-only">Bedrooms</label>
                            <select name="bedrooms" class="form-control">
                                <option selected="true" disabled="disabled">Bedrooms (Any)</option>
                                {% for key, value in bedroom_choices.items %}
                                <option value="{{ key }}">{{ value }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-6 mb-3">
                            <select name="price" class="form-control">
                                <option selected="true" disabled="disabled">Max Price (All)</option>
                                {% for key, value in price_choices.items %}
                                <option value="{{ key }}">{{ value }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
                </form>
            </div>
        </div>
    </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'main:main-index' %}">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'listing:index' %}">Browse Listings</a>
                </li>
                <li class="breadcrumb-item active"> Search Results</li>
            </ol>
        </nav>
    </div>
</section>

<!-- Listings -->
<section id="listings" class="py-4">
    <div class="container">
        <div class="row">
            {% if listings %}
            {% for listing in listings %}
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card">
                    <img class="card-img-top" height="200" src="{{listing.photo_main.url}}" alt="">
                    <div class="card-img-overlay">
                        <h2>
                            <span
                                class="badge badge-secondary text-white">${{listing.price | floatformat:0 | intcomma}}</span>
                        </h2>
                    </div>
                    <div class="card-body">
                        <div class="listing-heading text-center">
                            <h4 class="text-primary">{{listing.listing_title}}</h4>
                            <p>
                                <i class="fas fa-map-marker text-secondary"></i> {{listing.city}} {{listing.state}},
                                {{listing.zipcode}}</p>
                        </div>
                        <hr>
                        <div class="row py-2 text-secondary">
                            <div class="col-6">
                                <i class="fas fa-th-large"></i> Sqft: {{listing.sqft}}</div>
                            <div class="col-6">
                                <i class="fas fa-car"></i> Garage: {{listing.garage}}</div>
                        </div>
                        <div class="row py-2 text-secondary">
                            <div class="col-6">
                                <i class="fas fa-bed"></i> Bedrooms: {{listing.bedroom}}</div>
                            <div class="col-6">
                                <i class="fas fa-bath"></i> Bathrooms: {{listing.bathroom}}</div>
                        </div>
                        <hr>
                        <div class="row py-2 text-secondary">
                            <div class="col-12">
                                <i class="fas fa-user"></i> {{listing.realtor_id}}</div>
                        </div>
                        <div class="row text-secondary pb-2">
                            <div class="col-6">
                                <i class="fas fa-clock"></i> {{ listing.list_date | timesince }}</div>
                        </div>
                        <hr>
                        <a href="{% url 'listing:detail' listing.listing_id %}" class="btn btn-primary btn-block">More
                            Info</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-md-12">
                <p>There are no listings</p>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}